#!/usr/bin/env python3
"""Generate pure MoonBit extern bindings from dear_bindings metadata.

The generated `imgui/bindings` package is intentionally mechanical: it emits
MoonBit ABI declarations for the C API generated by dear_bindings and does not
generate C/C++ glue or handwritten MoonBit helpers.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any


RESERVED = {
    "as",
    "async",
    "break",
    "catch",
    "const",
    "continue",
    "derive",
    "else",
    "enum",
    "extern",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "is",
    "let",
    "loop",
    "match",
    "move",
    "priv",
    "pub",
    "raise",
    "return",
    "struct",
    "test",
    "trait",
    "try",
    "type",
    "var",
    "while",
    "with",
}


BUILTIN_TO_MOONBIT = {
    "bool": "Bool",
    "char": "Byte",
    "double": "Double",
    "float": "Float",
    "int": "Int",
    "long": "Int64",
    "long_long": "Int64",
    "short": "Int",
    "signed_char": "Byte",
    "signed_int": "Int",
    "signed_long": "Int64",
    "signed_long_long": "Int64",
    "signed_short": "Int",
    "unsigned_char": "Byte",
    "unsigned_int": "UInt",
    "unsigned_long": "UInt64",
    "unsigned_long_long": "UInt64",
    "unsigned_short": "UInt",
}


POINTER_RETURN_ALLOWLIST = {
    "ImGui_CreateContext",
    "ImGui_GetCurrentContext",
    "ImGui_GetDrawData",
    "ImGui_GetIO",
    "ImGui_GetStyle",
}


def to_snake(name: str) -> str:
    name = name.replace("::", "_").replace("-", "_")
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_").lower()
    if not name:
        name = "value"
    if name in RESERVED:
        name = f"{name}_"
    if name[0].isdigit():
        name = f"_{name}"
    return name


def literal_type(value: int) -> str:
    if -2147483648 <= value <= 2147483647:
        return "Int"
    if 0 <= value <= 4294967295:
        return "UInt"
    return "Int64"


def literal_value(value: int, typ: str) -> str:
    if typ == "UInt":
        return f"{value}U"
    if typ == "Int64":
        return f"{value}L"
    return str(value)


def parse_define(content: str | None) -> tuple[str, str] | None:
    if content is None:
        return None
    value = content.strip()
    if value.startswith('"') and value.endswith('"'):
        return ("String", value)
    if re.fullmatch(r"-?\d+", value):
        integer = int(value)
        typ = literal_type(integer)
        return (typ, literal_value(integer, typ))
    if re.fullmatch(r"0x[0-9A-Fa-f]+", value):
        integer = int(value, 16)
        typ = literal_type(integer)
        return (typ, literal_value(integer, typ))
    return None


def to_type_name(name: str, used: set[str]) -> str:
    raw = re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_")
    if not raw:
        raw = "AnonymousType"
    parts = [part for part in raw.split("_") if part]
    candidate = "".join(part[:1].upper() + part[1:] for part in parts)
    if not candidate or not candidate[0].isupper():
        candidate = f"Type{candidate}"
    base = candidate
    index = 2
    while candidate in used:
        candidate = f"{base}{index}"
        index += 1
    used.add(candidate)
    return candidate


def default_is_null(arg: dict[str, Any]) -> bool:
    return str(arg.get("default_value", "")).strip() == "NULL"


class UnsupportedType(Exception):
    pass


class BindingModel:
    def __init__(self, metadata: dict[str, Any]) -> None:
        self.metadata = metadata
        self.struct_names = {item["name"] for item in metadata["structs"]}
        self.typedefs = {item["name"]: item for item in metadata["typedefs"]}
        self.function_typedefs = {
            item["name"]: item
            for item in metadata["typedefs"]
            if item["type"]["description"].get("kind") == "Type"
            and item["type"]["description"].get("inner_type", {}).get("kind") == "Pointer"
            and item["type"]["description"]["inner_type"].get("inner_type", {}).get("kind")
            == "Function"
        }
        used_type_names: set[str] = set()
        self.struct_type_names = {
            name: to_type_name(name, used_type_names) for name in sorted(self.struct_names)
        }
        self.external_types: OrderedDict[str, str] = OrderedDict()
        for name in sorted(self.struct_names):
            self.external_types[name] = self.struct_type_names[name]
        self.used_function_names: set[str] = set()

    def moonbit_builtin(self, desc: dict[str, Any]) -> str:
        builtin = desc["builtin_type"]
        if builtin == "void":
            return "Unit"
        try:
            return BUILTIN_TO_MOONBIT[builtin]
        except KeyError as exc:
            raise UnsupportedType(f"unsupported builtin type `{builtin}`") from exc

    def is_function_pointer_typedef(self, name: str) -> bool:
        return name in self.function_typedefs

    def function_ref_type(self, name: str) -> str:
        typedef = self.function_typedefs[name]
        details = typedef["type"].get("type_details")
        if not details:
            raise UnsupportedType(f"function pointer typedef `{name}` has no details")
        ret = self.type_for_desc(details["return_type"]["description"], nullable=False, is_return=True)
        args = []
        for index, arg in enumerate(details.get("arguments", [])):
            args.append(
                self.type_for_desc(
                    arg["type"]["description"],
                    nullable=default_is_null(arg),
                    is_return=False,
                    arg_name=arg.get("name") or f"p{index}",
                )
            )
        if args:
            fn = f"({', '.join(args)}) -> {ret}"
        else:
            fn = f"() -> {ret}"
        return f"FuncRef[{fn}]"

    def resolve_user_type(self, name: str) -> str:
        if name in self.function_typedefs:
            return self.function_ref_type(name)
        if name in self.struct_names:
            self.external_types[name] = self.struct_type_names[name]
            return self.struct_type_names[name]
        typedef = self.typedefs.get(name)
        if typedef is None:
            return "Int"
        return self.type_for_desc(typedef["type"]["description"], nullable=False, is_return=False)

    def pointed_type(self, inner: dict[str, Any], nullable: bool) -> str:
        kind = inner.get("kind")
        if kind == "Builtin":
            builtin = inner["builtin_type"]
            if builtin == "char":
                return "Option[Ref[Byte]]" if nullable else "Bytes"
            if builtin == "void":
                return "VoidPtr"
            pointee = self.moonbit_builtin(inner)
            return f"Option[Ref[{pointee}]]" if nullable else f"Ref[{pointee}]"
        if kind == "User":
            name = inner["name"]
            if self.is_function_pointer_typedef(name):
                if nullable:
                    raise UnsupportedType(
                        f"nullable function pointer `{name}` is not representable without a thunk"
                    )
                return self.function_ref_type(name)
            pointee = self.resolve_user_type(name)
            if pointee in {"Bool", "Byte", "Int", "UInt", "Int64", "UInt64", "Float", "Double"}:
                return f"Option[Ref[{pointee}]]" if nullable else f"Ref[{pointee}]"
            return pointee
        if kind == "Pointer":
            nested = self.pointed_type(inner["inner_type"], nullable=False)
            return f"Option[Ref[{nested}]]" if nullable else f"Ref[{nested}]"
        if kind == "Type":
            return self.pointed_type(inner["inner_type"], nullable)
        raise UnsupportedType(f"unsupported pointer target `{kind}`")

    def type_for_desc(
        self,
        desc: dict[str, Any],
        *,
        nullable: bool,
        is_return: bool,
        arg_name: str = "",
    ) -> str:
        kind = desc.get("kind")
        if kind == "Builtin":
            return self.moonbit_builtin(desc)
        if kind == "User":
            if desc["name"] in self.struct_names and not is_return:
                raise UnsupportedType(f"struct value `{desc['name']}` must be passed by pointer")
            if desc["name"] in self.struct_names and is_return:
                raise UnsupportedType(f"struct return `{desc['name']}` is not ABI-direct")
            return self.resolve_user_type(desc["name"])
        if kind == "Pointer":
            return self.pointed_type(desc["inner_type"], nullable)
        if kind == "Array":
            inner = self.type_for_desc(desc["inner_type"], nullable=False, is_return=False)
            return f"FixedArray[{inner}]"
        if kind == "Type":
            return self.type_for_desc(desc["inner_type"], nullable=nullable, is_return=is_return)
        if kind == "Function":
            raise UnsupportedType("inline function type is not representable as a direct extern")
        raise UnsupportedType(f"unsupported type kind `{kind}`")

    def return_type(self, fn: dict[str, Any]) -> str:
        desc = fn["return_type"]["description"]
        if desc.get("kind") == "Pointer":
            return self.pointed_type(desc["inner_type"], nullable=True)
        return self.type_for_desc(desc, nullable=False, is_return=True)

    def arg_type(self, arg: dict[str, Any]) -> str:
        if arg.get("is_varargs"):
            raise UnsupportedType("C varargs are not ABI-direct")
        desc = arg["type"]["description"]
        nullable = default_is_null(arg)
        if desc.get("kind") == "Pointer":
            inner = desc.get("inner_type", {})
            is_required_c_string = (
                inner.get("kind") == "Builtin"
                and inner.get("builtin_type") == "char"
                and not nullable
            )
            if not is_required_c_string:
                nullable = True
        return self.type_for_desc(
            desc,
            nullable=nullable,
            is_return=False,
            arg_name=arg.get("name", ""),
        )

    def unique_function_name(self, symbol: str) -> str:
        base = to_snake(symbol)
        name = base
        index = 2
        while name in self.used_function_names:
            name = f"{base}_{index}"
            index += 1
        self.used_function_names.add(name)
        return name

    def emit_extern(self, fn: dict[str, Any]) -> tuple[list[str], str | None]:
        if fn.get("is_imstr_helper"):
            return [], "ImStr helper is not emitted by the pinned C ABI"
        try:
            ret = self.return_type(fn)
            params = [self.arg_type(arg) for arg in fn.get("arguments", [])]
        except UnsupportedType as exc:
            return [], str(exc)
        name = self.unique_function_name(fn["name"])
        bind_symbol = fn["name"]
        args = [f"_p{index} : {typ}" for index, typ in enumerate(params)]
        borrow = [f"_p{index}" for index, typ in enumerate(params) if typ == "Bytes"]
        lines = ["///|", f"/// Direct dear_bindings C ABI binding for `{bind_symbol}`."]
        for index, typ in enumerate(params):
            if (
                typ == "Bytes"
                or typ == "VoidPtr"
                or typ in self.external_types.values()
                or typ.startswith("Ref[")
                or typ.startswith("Option[Ref[")
                or typ.startswith("FixedArray[")
                or typ.startswith("FuncRef[")
            ) and f"_p{index}" not in borrow:
                borrow.append(f"_p{index}")
        if borrow:
            lines.append(f"#borrow({', '.join(borrow)})")
        if args:
            one_line = f'pub extern "C" fn {name}({", ".join(args)}) -> {ret} = "{bind_symbol}"'
            if len(one_line) <= 100:
                lines.append(one_line)
            else:
                lines.append(f'pub extern "C" fn {name}(')
                for arg in args:
                    lines.append(f"  {arg},")
                lines.append(f') -> {ret} = "{bind_symbol}"')
        else:
            lines.append(f'pub extern "C" fn {name}() -> {ret} = "{bind_symbol}"')
        return lines, None


def generate(metadata: dict[str, Any]) -> tuple[str, str, str]:
    model = BindingModel(metadata)
    lines: list[str] = [
        "///|",
        "/// Pure MoonBit extern bindings generated from `dcimgui.json`.",
        "///",
        "/// This package contains no hand-written bridge code. Pointer ABI follows",
        "/// MoonBit native rules: `Bytes` for non-null UTF-8 `char*`, `Ref[T]`",
        "/// for primitive `T*`, `Option[Ref[T]]` for nullable primitive `T*`,",
        "/// and direct `#external` handle types for C pointers represented by",
        "/// external types.",
        "",
        "///|",
        "/// Opaque ABI carrier for `void*` values.",
        "#external",
        "pub(all) type VoidPtr",
        "",
        "///|",
        "/// Null `VoidPtr` handle.",
        'pub extern "C" fn VoidPtr::null() -> VoidPtr = "moonbit_imgui_null"',
        "",
        "///|",
        "/// Returns true when this `VoidPtr` handle is null.",
        "#borrow(self)",
        'pub extern "C" fn VoidPtr::is_null(self : VoidPtr) -> Bool = "moonbit_is_null"',
        "",
    ]

    for c_name, moonbit_name in model.external_types.items():
        lines.extend(
            [
                "///|",
                f"/// Opaque C pointer handle for `{c_name}`.",
                "#external",
                f"pub(all) type {moonbit_name}",
                "",
                "///|",
                f"/// Null `{moonbit_name}` handle.",
                f'pub extern "C" fn {moonbit_name}::null() -> {moonbit_name} = "moonbit_imgui_null"',
                "",
                "///|",
                f"/// Returns true when this `{moonbit_name}` handle is null.",
                "#borrow(self)",
                f'pub extern "C" fn {moonbit_name}::is_null(self : {moonbit_name}) -> Bool = "moonbit_is_null"',
                "",
            ]
        )

    alias_lines: list[str] = []
    used_alias_names: set[str] = set()
    for typedef in metadata["typedefs"]:
        name = typedef["name"]
        if name in used_alias_names:
            continue
        if name in model.struct_names or name in model.function_typedefs:
            continue
        try:
            typ = model.resolve_user_type(name)
        except UnsupportedType:
            continue
        if typ in {"Bool", "Byte", "Int", "UInt", "Int64", "UInt64", "Float", "Double"}:
            used_alias_names.add(name)
            alias_lines.extend(["///|", f"/// ABI alias for C typedef `{name}`.", f"pub type {name} = {typ}", ""])
    lines.extend(alias_lines)

    for typedef in metadata["typedefs"]:
        name = typedef["name"]
        if name in used_alias_names:
            continue
        if name not in model.function_typedefs:
            continue
        try:
            typ = model.function_ref_type(name)
        except UnsupportedType:
            continue
        used_alias_names.add(name)
        lines.extend(["///|", f"/// ABI alias for C function pointer typedef `{name}`.", f"pub type {name} = {typ}", ""])

    skipped_defines: list[tuple[str, str]] = []
    used_constant_names: set[str] = set()
    for define in metadata["defines"]:
        if define.get("is_internal"):
            continue
        fn_name = to_snake(define["name"])
        if fn_name in used_constant_names:
            skipped_defines.append((define["name"], "duplicate generated name"))
            continue
        parsed = parse_define(define.get("content"))
        if parsed is None:
            skipped_defines.append((define["name"], "macro is not a literal numeric or string value"))
            continue
        typ, value = parsed
        used_constant_names.add(fn_name)
        lines.extend(
            [
                "///|",
                f"/// Generated constant binding for define `{define['name']}`.",
                f"pub fn {fn_name}() -> {typ} {{",
                f"  {value}",
                "}",
                "",
            ]
        )

    for enum in metadata["enums"]:
        if enum.get("is_internal"):
            continue
        for element in enum["elements"]:
            if element.get("is_internal"):
                continue
            fn_name = to_snake(element["name"])
            if fn_name in used_constant_names:
                continue
            used_constant_names.add(fn_name)
            value = int(element["value"])
            wrapped = value - 2**32 if value > 2147483647 else value
            lines.extend(
                [
                    "///|",
                    f"/// Generated constant binding for enum value `{element['name']}`.",
                    f"pub fn {fn_name}() -> Int {{",
                    f"  {wrapped}",
                    "}",
                    "",
                ]
            )

    skipped_functions: list[tuple[str, str]] = []
    emitted = 0
    for fn in metadata["functions"]:
        emitted_lines, reason = model.emit_extern(fn)
        if reason is not None:
            skipped_functions.append((fn["name"], reason))
            continue
        emitted += 1
        lines.extend(emitted_lines)
        lines.append("")

    text = "\n".join(lines).rstrip() + "\n"

    coverage = [
        "# Generated Binding Coverage",
        "",
        "This report is generated from `dcimgui.json`.",
        "",
        f"- Struct external types: {len(model.external_types)} / {len(metadata['structs'])}",
        f"- Typedefs: {len(metadata['typedefs'])}",
        f"- Defines emitted: {len(metadata['defines']) - len(skipped_defines)} / {len(metadata['defines'])}",
        f"- Enum values emitted: {sum(len(e['elements']) for e in metadata['enums'] if not e.get('is_internal'))}",
        f"- C functions emitted: {emitted} / {len(metadata['functions'])}",
        "",
    ]
    if skipped_defines:
        coverage.append("## Skipped Defines")
        coverage.append("")
        for name, reason in skipped_defines:
            coverage.append(f"- `{name}`: {reason}")
        coverage.append("")
    if skipped_functions:
        coverage.append("## Skipped Functions")
        coverage.append("")
        for name, reason in skipped_functions:
            coverage.append(f"- `{name}`: {reason}")
        coverage.append("")
    runtime_c = """/* Generated by tools/generate_bindings.py. */
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

void* moonbit_imgui_null(void) {
  return NULL;
}

#ifdef __cplusplus
}
#endif
"""
    return text, "\n".join(coverage).rstrip() + "\n", runtime_c


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True, type=Path)
    parser.add_argument("--moonbit-out", required=True, type=Path)
    parser.add_argument("--coverage-out", required=True, type=Path)
    parser.add_argument("--c-out", required=True, type=Path)
    args = parser.parse_args()

    metadata = json.loads(args.metadata.read_text())
    moonbit, coverage, runtime_c = generate(metadata)
    args.moonbit_out.parent.mkdir(parents=True, exist_ok=True)
    args.moonbit_out.write_text(moonbit)
    args.coverage_out.write_text(coverage)
    args.c_out.write_text(runtime_c)


if __name__ == "__main__":
    main()
